name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  
  build:
    runs-on: ${{ matrix.operating-system }}    
    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python: [3.8.1]
        poetry-version: [1.1.12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install dependencies
        run: |
              poetry install
      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "22.3.0"
          
      - name: Test with pytest
        run: | 
              poetry run pytest
        env:
            KAFKA_TOPIC: test-topic
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: localhost
            DATABASE_SCHEMA: testdb
            DATABASE_PORT: 5432